language: en
pipeline:
  - name: SpacyNLP
    model: external_data/output
  - name: SpacyTokenizer
  - name: CountVectorsFeaturizer
  - name: DIETClassifier
    epochs: 200
    random_seed: 2
  - name: EntitySynonymMapper
  - name: FallbackClassifier
    threshold: 0.4

policies:
  - name: MemoizationPolicy
    max_history: 3
  - name: TEDPolicy
    max_history: 3
    epochs: 60
    random_seed: 5
    validation_split: 0.2
  - name: RulePolicy
    core_fallback_threshold: 0.4
    core_fallback_action_name: "action_my_fallback"
    enable_fallback_prediction: false
