language: en
pipeline:
  - name: SpacyNLP
    model: external_data/output
  - name: SpacyTokenizer
  - name: CountVectorsFeaturizer
  - name: DIETClassifier
    epochs: 70
    random_seed: 2
  - name: EntitySynonymMapper

policies:
  - name: MemoizationPolicy
    max_history: 3
  - name: TEDPolicy
    max_history: 3
    epochs: 60
    random_seed: 5
    validation_split: 0.2
  - name: RulePolicy
